name: 'On Push' 

on:
    push:
        branches-ignore: 'master'

jobs:
    CI-apex-test-run:
        runs-on: ubuntu-latest
        container: salesforce/salesforcedx

        steps:
            - uses: actions/checkout@v1

            - name: Populate jwt key file
              run: openssl enc -nosalt -aes-256-cbc -d -in .github/server.key.enc -out .github/server.key -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}

            - name: Authenticate against dev hub
              run: sfdx force:auth:jwt:grant --clientid ${{ secrets.CONSUMERKEY }} --jwtkeyfile .github/server.key --username ${{ secrets.USERNAME }} --setdefaultdevhubusername -a devhub

            - name: Create scratch org
              run: sfdx force:org:create --definitionfile=config/project-scratch-def.json --setalias=scratch-org --setdefaultusername

            - name: Push source
              run: sfdx force:source:push

            - name: Run tests
              run: sfdx force:apex:test:run --codecoverage --resultformat=tap

            - name: Clean up scratch org
              run: sfdx force:org:delete --targetusername=scratch-org --noprompt
